import { StyleSheet, Dimensions } from 'react-native';

const screenWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    contentContainer: {
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#201925',
    },
    loadingText: {
        color: '#fff',
        fontSize: 16,
        marginTop: 10,
    },
    header: {
        padding: 20,
        paddingBottom: 10,
    },
    heading: {
        color: '#ffffff',
        fontSize: 24,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    subheading: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 20,
        fontWeight: '500',
    },
    errorText: {
        color: '#e74c3c',
        fontSize: 14,
        textAlign: 'center',
        margin: 16,
        padding: 10,
        backgroundColor: 'rgba(231, 76, 60, 0.1)',
        borderRadius: 8,
    },
    phaseIndicator: {
        flexDirection: 'column',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderColor: 'rgba(64, 51, 71, 0.3)',
        borderWidth: 1,
        borderRadius: 16,
        padding: 16,
    },
    combinedCard: {
        flexDirection: 'column',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderColor: 'rgba(64, 51, 71, 0.3)',
        borderWidth: 1,
        borderRadius: 16,
        padding: 16,
        marginTop: 24,
    },
    collectingTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        textAlign: 'center',
        marginBottom: 16,
        opacity: 1,
    },
    cardTitle: {
        color: '#fff',
        fontSize: 24,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        textAlign: 'center',
        marginBottom: 20,
    },
    submissionCountContainer: {
        alignItems: 'center',
    },
    submissionCount: {
        color: '#cc31e8',
        fontSize: 48,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        lineHeight: 52,
    },
    submissionLabel: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 16,
        fontFamily: 'Montserrat_400Regular',
        marginTop: 4,
    },
    phaseContent: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    phaseTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    subtleActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(103, 115, 234, 0.15)',
        borderColor: 'rgba(103, 115, 234, 0.3)',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 10,
        alignSelf: 'flex-start',
        marginBottom: 12,
    },
    subtleActionButtonText: {
        color: '#cc31e8',
        fontSize: 13,
        fontWeight: '600',
        marginLeft: 8,
    },
    shareButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#201925',
        borderRadius: 8,
        borderWidth: 1.5,
        borderColor: '#cc31e8',
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginHorizontal: 16,
        marginBottom: 20,
        alignSelf: 'flex-start',
        flexShrink: 1,
    },
    shareButtonText: {
        color: '#cc31e8',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    phaseSubtitle: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 16,
        lineHeight: 20,
    },
    phaseActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cc31e8',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 12,
        width: '100%',
    },
    phaseActionButtonText: {
        color: '#fff',
        fontWeight: '600',
        marginLeft: 8,
    },
    progressBarContainer: {
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 3,
        marginHorizontal: 16,
        marginBottom: 16,
        overflow: 'hidden',
    },
    progressBar: {
        height: '100%',
        backgroundColor: '#cc31e8',
        borderRadius: 3,
    },
    availabilitySection: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(64, 51, 71, 0.3)',
        marginHorizontal: 16,
        marginBottom: 12,
        padding: 16,
    },
    availabilityHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    availabilityTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    availabilityEmptyText: {
        color: '#ccc',
        fontSize: 14,
    },
    participantAvailability: {
        marginBottom: 16,
    },
    participantName: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
    },
    availabilityGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    dateCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 8,
        padding: 12,
        minWidth: 120,
        marginBottom: 8,
    },
    dateHeader: {
        color: '#cc31e8',
        fontSize: 12,
        fontWeight: '600',
        marginBottom: 8,
    },
    timeSlots: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
    },
    timeSlot: {
        backgroundColor: 'rgba(102, 126, 234, 0.2)',
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    timeSlotText: {
        color: '#cc31e8',
        fontSize: 11,
    },
    overlapAnalysis: {
        marginTop: 16,
        paddingTop: 16,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
        borderTopWidth: 1,
    },
    overlapTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    overlapTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    bestTimeCard: {
        backgroundColor: 'rgba(40, 167, 69, 0.1)',
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
    },
    bestTimeDateHeader: {
        color: '#28a745',
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
    },
    participantCountText: {
        fontWeight: 'normal',
        color: 'rgba(40, 167, 69, 0.8)',
    },
    timeOverlapItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    timeText: {
        color: '#fff',
        fontSize: 13,
    },
    availabilityBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 12,
    },
    availabilityBadgeText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '600',
    },
    preferencesCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        alignItems: 'center',
        borderColor: 'rgba(64, 51, 71, 0.3)',
        borderWidth: 1,
    },
    preferencesSection: {
        alignItems: 'center',
        marginTop: 16,
        paddingTop: 16,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
        borderTopWidth: 1,
        width: '100%',
    },
    submittedSection: {
        alignItems: 'center',
        marginTop: 16,
        paddingTop: 16,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
        borderTopWidth: 1,
        width: '100%',
    },
    generateButtonContainer: {
        marginHorizontal: 24,
        marginTop: 20,
        marginBottom: 20,
    },
    generateButtonGradientBorder: {
        borderRadius: 24,
        padding: 3,
        shadowColor: 'rgba(185, 84, 236, 0.6)',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 1,
        shadowRadius: 16,
        elevation: 16,
    },
    generateButtonInner: {
        borderRadius: 21,
        backgroundColor: 'rgba(32, 25, 37, 0.95)',
        overflow: 'hidden',
    },
    generateButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 18,
        gap: 16,
    },
    generateButtonIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        position: 'relative',
    },
    generateIconGlow: {
        position: 'absolute',
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(185, 84, 236, 0.3)',
        shadowColor: '#B954EC',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
    },
    generateTextContainer: {
        flex: 1,
    },
    generateButtonText: {
        color: '#ffffff',
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 4,
        fontFamily: 'Montserrat_700Bold',
        includeFontPadding: false,
        textAlignVertical: 'top',
    },
    generateButtonSubtext: {
        color: 'rgba(255, 255, 255, 0.75)',
        fontSize: 13,
        fontWeight: '500',
        includeFontPadding: false,
        textAlignVertical: 'top',
        paddingLeft: 8,
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        gap: 8,
        width: '100%',
        marginTop: 16,
    },
    saveButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#28a745',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        flex: 1,
    },
    saveButtonText: {
        color: '#fff',
        fontWeight: '600',
        marginLeft: 6,
        fontSize: 14,
    },
    finalizeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cc31e8',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        flex: 1,
    },
    finalizeButtonText: {
        color: '#fff',
        fontWeight: '600',
        marginLeft: 6,
        fontSize: 14,
    },
    preferencesTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        marginTop: 12,
        marginBottom: 8,
        textAlign: 'center',
    },
    preferencesText: {
        color: 'rgba(255, 255, 255, 0.95)',
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 20,
    },
    preferencesButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#cc31e8',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
    },
    preferencesButtonText: {
        color: '#fff',
        fontWeight: '600',
        marginLeft: 8,
    },
    submittedCard: {
        backgroundColor: 'rgba(16, 185, 129, 0.05)',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        marginHorizontal: 16,
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.2)',
    },
    submittedTitle: {
        color: '#28a745',
        fontSize: 18,
        fontWeight: '700',
        marginTop: 12,
        marginBottom: 8,
        textAlign: 'center',
    },
    submittedText: {
        color: 'rgba(255, 255, 255, 0.95)',
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 20,
    },
    resubmitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'transparent',
        borderColor: '#cc31e8',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
    },
    resubmitButtonText: {
        color: '#cc31e8',
        fontWeight: '600',
        marginLeft: 8,
    },
    recommendationsList: {
        marginTop: 32,
        marginBottom: 16,
    },
    listItem: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 12,
        marginBottom: 12,
        borderColor: 'rgba(64, 51, 71, 0.3)',
        borderWidth: 1,
        overflow: 'hidden',
    },
    selectedListItem: {
        borderColor: '#28a745',
        borderWidth: 2,
    },
    selectedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#28a745',
        paddingHorizontal: 12,
        paddingVertical: 6,
        justifyContent: 'center',
    },
    selectedBadgeText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 12,
        marginLeft: 6,
    },
    listContent: {
        padding: 16,
    },
    listTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    listName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        flex: 1,
        marginRight: 12,
    },
    listMeta: {
        color: '#D4AF37',
        fontSize: 14,
        fontWeight: '600',
    },
    listBottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
    listDetail: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 13,
        marginBottom: 2,
    },
    voteSection: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    likeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderWidth: 1,
    },
    likedButton: {
        backgroundColor: 'rgba(231, 76, 60, 0.2)',
        borderColor: '#e74c3c',
    },
    likeButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
        marginLeft: 6,
    },
    voteCount: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    voteCountText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 13,
        fontWeight: '600',
        marginLeft: 4,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    votingModalContainer: {
        width: '90%',
        maxWidth: 380,
        borderRadius: 24,
        overflow: 'hidden',
        backgroundColor: '#1A1625',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.4,
        shadowRadius: 20,
        elevation: 15,
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.2)',
    },
    modalGradientBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 140,
    },
    logoWrapper: {
        alignSelf: 'center',
        marginTop: 60,
        marginBottom: -35,
        zIndex: 5,
    },
    logoCircle: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 10,
    },
    logoImage: {
        width: 75,
        height: 75,
    },
    modalContentWrapper: {
        backgroundColor: 'transparent',
    },
    modernCloseBtn: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 10,
    },
    closeBtnCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    modalIconWrapper: {
        alignSelf: 'center',
        marginTop: 60,
        marginBottom: -35,
        zIndex: 5,
    },
    iconCircle: {
        width: 70,
        height: 70,
        borderRadius: 35,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
    },
    votingModalContent: {
        backgroundColor: '#1A1625',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingTop: 50,
        alignItems: 'center',
    },
    modernTitle: {
        color: '#FFFFFF',
        fontSize: 26,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 8,
    },
    modernDescription: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 24,
        paddingHorizontal: 16,
    },
    modernProgressSection: {
        width: '100%',
        backgroundColor: 'rgba(147, 51, 234, 0.1)',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.2)',
    },
    progressHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    usersIconWrapper: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(168, 85, 247, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    progressLabel: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 14,
        fontWeight: '600',
    },
    modernProgressBarBg: {
        width: '100%',
        height: 8,
        backgroundColor: 'rgba(147, 51, 234, 0.2)',
        borderRadius: 4,
        overflow: 'hidden',
        marginBottom: 12,
    },
    modernProgressFill: {
        height: '100%',
        borderRadius: 4,
    },
    progressInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    progressText: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 13,
    },
    percentageBadge: {
        backgroundColor: 'rgba(168, 85, 247, 0.2)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    percentageText: {
        color: '#A855F7',
        fontSize: 14,
        fontWeight: '700',
    },
    modernWarning: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(251, 191, 36, 0.1)',
        borderRadius: 12,
        padding: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(251, 191, 36, 0.2)',
    },
    warningIconCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: 'rgba(251, 191, 36, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    modernWarningText: {
        color: '#FBBF24',
        fontSize: 13,
        flex: 1,
        fontWeight: '500',
    },
    buttonContainer: {
        flexDirection: 'row',
        width: '100%',
        gap: 12,
    },
    secondaryButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: 'rgba(147, 51, 234, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.3)',
    },
    secondaryButtonText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 15,
        fontWeight: '600',
        textAlign: 'center',
    },
    primaryButton: {
        flex: 1.5,
        borderRadius: 12,
        overflow: 'hidden',
        shadowColor: '#8B5CF6',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    primaryButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        gap: 8,
    },
    primaryButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
    },
    votingModalCloseButton: {
        position: 'absolute',
        top: 20,
        right: 20,
        padding: 12,
        zIndex: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    votingModalTitle: {
        color: '#fff',
        fontSize: 22,
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 12,
    },
    votingModalDescription: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 24,
    },
    votingModalProgressSection: {
        width: '100%',
        marginBottom: 20,
    },
    votingModalButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cc31e8',
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 12,
        width: '100%',
        marginTop: 10,
    },
    votingModalButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        marginLeft: 8,
    },
    modalContainer: {
        backgroundColor: '#2C1E33',
        borderRadius: 16,
        width: '100%',
        maxWidth: 400,
        maxHeight: '80%',
    },
    modalHeader: {
        padding: 20,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
        borderBottomWidth: 1,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        textAlign: 'center',
    },
    modalSubtitle: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 4,
    },
    modalCloseButton: {
        position: 'absolute',
        top: 15,
        right: 15,
        padding: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 20,
        zIndex: 10,
    },
    modalBody: {
        padding: 20,
    },
    modalProgressContainer: {
        marginBottom: 16,
    },
    progressLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    progressPercentage: {
        color: '#cc31e8',
        fontSize: 14,
        fontWeight: '600',
    },
    warningBox: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: 'rgba(255, 193, 7, 0.1)',
        borderColor: 'rgba(255, 193, 7, 0.3)',
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
        width: '100%',
    },
    warningIcon: {
        marginRight: 8,
        marginTop: 2,
    },
    warningText: {
        color: '#ffc107',
        fontSize: 13,
        flex: 1,
        lineHeight: 18,
    },
    detailModal: {
        flex: 1,
        backgroundColor: '#201925',
    },
    modalActionButtons: {
        flexDirection: 'row',
        padding: 20,
        paddingTop: 16,
        marginTop: 12,
        gap: 12,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
    },
    modalActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 14,
        borderRadius: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        gap: 8,
    },
    modalActionButtonActive: {
        backgroundColor: 'rgba(231, 76, 60, 0.1)',
        borderColor: '#e74c3c',
    },
    modalActionButtonText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        fontWeight: '600',
    },
    modalActionButtonTextActive: {
        color: '#e74c3c',
    },
    modalFavoriteButton: {
        backgroundColor: 'rgba(147, 51, 234, 0.1)',
        borderColor: 'rgba(147, 51, 234, 0.3)',
    },
    modalFavoriteButtonActive: {
        backgroundColor: 'rgba(212, 175, 55, 0.15)',
        borderColor: '#D4AF37',
    },
    modalFavoriteButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    modalFavoriteButtonTextActive: {
        color: '#D4AF37',
    },
    detailModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
        borderBottomWidth: 1,
    },
    detailModalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        flex: 1,
        textAlign: 'center',
        paddingRight: 40,
    },
    detailCloseButton: {
        position: 'absolute',
        top: 10,
        right: 15,
        padding: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 20,
        zIndex: 10,
    },
    detailModalBody: {
        flex: 1,
        padding: 20,
    },
    detailGrid: {
        marginBottom: 20,
    },
    detailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    detailLabel: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        marginLeft: 8,
        marginRight: 8,
    },
    detailValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    hoursContainer: {
        flex: 1,
        marginLeft: 8,
    },
    hoursRow: {
        flexDirection: 'row',
        marginBottom: 4,
    },
    hoursDays: {
        color: '#B8A5C4',
        fontSize: 13,
        fontWeight: '600',
        minWidth: 65,
    },
    hoursTime: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '500',
        flex: 1,
    },
    section: {
        marginBottom: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionHeaderText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    description: {
        color: 'rgba(255, 255, 255, 0.95)',
        fontSize: 14,
        lineHeight: 20,
    },
    addressLink: {
        color: '#A855F7',
        textDecorationLine: 'underline',
        fontSize: 14,
        lineHeight: 20,
    },
    websiteLink: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        paddingVertical: 8,
    },
    websiteLinkText: {
        color: '#cc31e8',
        fontSize: 14,
        fontWeight: '600',
        marginHorizontal: 6,
    },
    reason: {
        backgroundColor: 'rgba(102, 126, 234, 0.1)',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
    },
    reasonTitle: {
        color: '#cc31e8',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 8,
    },
    reasonText: {
        color: 'rgba(255, 255, 255, 0.95)',
        fontSize: 14,
        lineHeight: 20,
    },
    photoSection: {
        marginBottom: 20,
    },
    photo: {
        width: 120,
        height: 120,
        borderRadius: 8,
        marginRight: 12,
    },
    reviewItem: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
    },
    reviewHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    reviewAuthor: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    reviewRating: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    reviewRatingText: {
        color: '#D4AF37',
        fontSize: 12,
        marginLeft: 4,
    },
    reviewText: {
        color: 'rgba(255, 255, 255, 0.95)',
        fontSize: 13,
        lineHeight: 18,
    },
    reviewToggleButton: {
        color: '#cc31e8',
        fontWeight: '600',
        textDecorationLine: 'underline',
    },
    fallbackText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 16,
        textAlign: 'center',
        margin: 20,
    },

    // Exciting Loading Modal Styles
    loadingModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingModalContainer: {
        backgroundColor: '#2C1E33',
        borderRadius: 30,
        padding: 50,
        alignItems: 'center',
        maxWidth: 350,
        margin: 20,
        shadowColor: '#6B73FF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 10,
        borderWidth: 1,
        borderColor: 'rgba(107, 115, 255, 0.3)',
    },
    loadingAnimation: {
        position: 'relative',
        width: 80,
        height: 80,
        marginBottom: 30,
    },
    loadingCircle: {
        position: 'absolute',
        borderWidth: 3,
        borderRadius: 40,
        borderColor: 'transparent',
    },
    loadingCircle1: {
        width: 80,
        height: 80,
        borderTopColor: '#6B73FF',
        borderRightColor: '#6B73FF',
    },
    loadingCircle2: {
        width: 60,
        height: 60,
        top: 10,
        left: 10,
        borderTopColor: '#9D50BB',
        borderRightColor: '#9D50BB',
    },
    loadingCircle3: {
        width: 40,
        height: 40,
        top: 20,
        left: 20,
        borderTopColor: '#CF38DD',
        borderRightColor: '#CF38DD',
    },
    voxxyTriangleContainer: {
        width: 100,
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    voxxyTriangle: {
        width: 80,
        height: 80,
        tintColor: undefined, // Let the image use its natural colors
    },
    loadingModalTitle: {
        color: '#fff',
        fontSize: 24,
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 15,
        letterSpacing: 0.5,
    },
    loadingModalSubtitle: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 10,
        paddingHorizontal: 10,
    },
    loadingModalTimeEstimate: {
        color: '#FFE66D',
        fontSize: 14,
        textAlign: 'center',
        fontWeight: '600',
        marginBottom: 25,
        paddingHorizontal: 10,
    },
    loadingDots: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    loadingDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#6B73FF',
    },
    loadingDot1: {
        backgroundColor: '#6B73FF',
    },
    loadingDot2: {
        backgroundColor: '#9D50BB',
    },
    loadingDot3: {
        backgroundColor: '#CF38DD',
    },

    // Swipeable Card Styles
    swipeContainer: {
        flex: 1,
        backgroundColor: '#201925',
    },
    swipeHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        paddingBottom: 8,
    },
    swipeBackButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    swipeHeaderCenter: {
        flex: 1,
        alignItems: 'center',
    },
    swipeHeaderRight: {
        width: 40, // Balance the back button
    },
    swipeHeaderTitle: {
        color: '#fff',
        fontSize: 24,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        marginBottom: 0,
    },
    cardCounter: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    cardCounterText: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 14,
        fontWeight: '600',
    },
    swipeInstructions: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingHorizontal: 40,
        paddingVertical: 8,
        marginBottom: -8,
    },
    instructionItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    swipeLeftDemo: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(231, 76, 60, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
    },
    swipeRightDemo: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(40, 167, 69, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
    },
    instructionText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 13,
        fontWeight: '500',
    },
    cardStack: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    swipeCard: {
        width: screenWidth - 40,
        height: 220,  // Reduced height for cleaner cards like Try Voxxy
        borderRadius: 16,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    activeCard: {
        position: 'absolute',
        zIndex: 1,
    },
    nextCard: {
        position: 'absolute',
        zIndex: -1,
        transform: [{ scale: 0.95 }],
        opacity: 0.6,
    },
    cardGradient: {
        flex: 1,
        borderRadius: 16,
        padding: 16,
        justifyContent: 'flex-start',
        borderWidth: 1,
        borderColor: 'rgba(204, 49, 232, 0.2)',
    },
    swipeIndicator: {
        position: 'absolute',
        top: 30,
        zIndex: 10,
        alignItems: 'center',
        justifyContent: 'center',
        width: 90,
        height: 90,
        borderRadius: 45,
        borderWidth: 4,
    },
    likeIndicator: {
        right: 25,
        borderColor: '#28a745',
        backgroundColor: 'rgba(40, 167, 69, 0.25)',
    },
    dislikeIndicator: {
        left: 25,
        borderColor: '#e74c3c',
        backgroundColor: 'rgba(231, 76, 60, 0.25)',
    },
    likeText: {
        color: '#28a745',
        fontSize: 14,
        fontWeight: '800',
        marginTop: 4,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    dislikeText: {
        color: '#e74c3c',
        fontSize: 14,
        fontWeight: '800',
        marginTop: 4,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    cardTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        flex: 1,
        marginRight: 12,
    },
    cardPrice: {
        color: '#cc31e8',
        fontSize: 16,
        fontWeight: '600',
    },
    cardDetails: {
        marginBottom: 16,
    },
    cardDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    cardDetailText: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 14,
        marginLeft: 8,
    },
    cardDescription: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 12,
    },
    cardAddressRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 16,
    },
    cardAddressText: {
        color: '#B8A5C4',
        fontSize: 13,
        flex: 1,
    },
    cardReason: {
        backgroundColor: 'rgba(102, 126, 234, 0.15)',
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
    },
    cardReasonTitle: {
        color: '#cc31e8',
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 4,
    },
    cardReasonText: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 13,
        lineHeight: 18,
    },
    cardActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
    },
    cardActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 1,
    },
    flagButton: {
        borderColor: '#ffc107',
        backgroundColor: 'rgba(255, 193, 7, 0.1)',
    },
    flagButtonText: {
        color: '#ffc107',
        fontSize: 13,
        fontWeight: '600',
        marginLeft: 6,
    },
    favoriteButton: {
        borderColor: '#D4AF37',
        backgroundColor: 'rgba(212, 175, 55, 0.1)',
    },
    favoriteButtonText: {
        color: '#D4AF37',
        fontSize: 13,
        fontWeight: '600',
        marginLeft: 6,
    },
    nextCardTitle: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 18,
        fontWeight: '600',
        textAlign: 'center',
        marginTop: 20,
    },
    skipButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 25,
        marginHorizontal: 20,
        marginBottom: 20,
    },
    skipButtonText: {
        color: '#cc31e8',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },

    // Results View Styles
    resultsHeader: {
        padding: 16,
        marginBottom: 16,
    },
    resultsStats: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(64, 51, 71, 0.3)',
    },
    statItem: {
        alignItems: 'center',
    },
    statNumber: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        marginTop: 6,
    },
    statLabel: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 11,
        marginTop: 2,
    },
    favoriteListItem: {
        borderColor: '#D4AF37',
        borderWidth: 2,
    },
    favoriteIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#D4AF37',
        paddingHorizontal: 12,
        paddingVertical: 6,
        justifyContent: 'center',
    },
    favoriteIndicatorText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 12,
        marginLeft: 6,
    },
    finalActionsContainer: {
        flexDirection: 'row',
        gap: 12,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    finalizeFromResultsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#28a745',
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderRadius: 12,
        flex: 1,
    },
    finalizeFromResultsButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        marginLeft: 8,
    },
    resetButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        borderColor: '#cc31e8',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
        marginHorizontal: 16,
        marginBottom: 20,
    },
    resetButtonText: {
        color: '#cc31e8',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    noLikesContainer: {
        alignItems: 'center',
        padding: 40,
        marginHorizontal: 16,
    },
    noLikesTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        marginTop: 16,
        marginBottom: 8,
    },
    noLikesText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 24,
    },
    tryAgainButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#cc31e8',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 12,
    },
    tryAgainButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },

    // No recommendations styles
    noRecommendationsContainer: {
        alignItems: 'center',
        padding: 40,
        marginHorizontal: 16,
    },
    noRecommendationsTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        marginTop: 16,
        marginBottom: 8,
    },
    noRecommendationsText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 24,
    },
    generateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#cc31e8',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 12,
    },
    generateButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },

    // Voting placeholder styles
    votingPlaceholder: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
        marginHorizontal: 16,
    },
    votingPlaceholderText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 16,
        textAlign: 'center',
    },

    // Test button styles
    testButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingHorizontal: 40,
        paddingVertical: 20,
    },
    testButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 25,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    testButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },

    // Phase-specific button styles
    activateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cc31e8',
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 12,
        marginTop: 16,
    },
    activateButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        marginLeft: 8,
    },
    startCollectingButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#28a745',
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 12,
        marginTop: 16,
    },
    startCollectingButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        marginLeft: 8,
    },

    // Debug styles
    debugInfo: {
        marginTop: 20,
        padding: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderRadius: 8,
    },
    debugText: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 12,
        fontFamily: 'monospace',
    },

    // Combined results card styles
    combinedResultsCard: {
        marginHorizontal: 16,
        marginBottom: 20,
        padding: 24,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(64, 51, 71, 0.3)',
    },
    resultsTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        marginLeft: 8,
    },
    resultsSubtitle: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 20,
    },
    actionButtons: {
        gap: 12,
    },
    statsCard: {
        marginHorizontal: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(64, 51, 71, 0.2)',
    },
    primaryActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cc31e8',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 12,
        elevation: 3,
        shadowColor: '#cc31e8',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    primaryActionButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginRight: 8,
    },
    saveFavoriteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#D4AF37',
        paddingVertical: 14,
        borderRadius: 12,
        elevation: 3,
        shadowColor: '#D4AF37',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    finalizeActivityButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cc31e8',
        paddingVertical: 14,
        borderRadius: 12,
        elevation: 3,
        shadowColor: '#cc31e8',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    saveFavoriteButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        marginLeft: 8,
    },
    finalizeActivityButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        marginLeft: 8,
    },
    generateButtonDisabled: {
        opacity: 0.5,
    },
    modernHeader: {
        alignItems: 'center',
        marginTop: 16,
        marginBottom: 16,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.2)',
        marginBottom: 12,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#10B981',
        marginRight: 6,
    },
    statusText: {
        color: '#10B981',
        fontSize: 12,
        fontWeight: '600',
    },
    modernCollectingTitle: {
        color: '#FFFFFF',
        fontSize: 24,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 4,
    },
    modernSubtitle: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 14,
        textAlign: 'center',
    },
    statsGradient: {
        padding: 20,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.2)',
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        marginBottom: 20,
    },
    bigNumber: {
        color: '#A855F7',
        fontSize: 36,
        fontWeight: '800',
        marginBottom: 4,
    },
    divider: {
        width: 1,
        height: 40,
        backgroundColor: 'rgba(147, 51, 234, 0.2)',
    },
    percentageCircle: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(168, 85, 247, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#A855F7',
    },
    percentageNumber: {
        color: '#A855F7',
        fontSize: 18,
        fontWeight: '700',
    },
    modernProgressContainer: {
        width: '100%',
    },
    modernProgressBg: {
        width: '100%',
        height: 6,
        backgroundColor: 'rgba(147, 51, 234, 0.1)',
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressGradientFill: {
        width: '100%',
        height: '100%',
    },
    actionCard: {
        borderRadius: 20,
        overflow: 'hidden',
        marginBottom: 8,
        marginHorizontal: 16,
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    socialActionContainer: {
        paddingHorizontal: 16,
        paddingTop: 20,
        paddingBottom: 8,
    },
    userHeaderSection: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(64, 51, 71, 0.3)',
    },
    userAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        marginRight: 12,
        borderWidth: 2,
        borderColor: '#8b5cf6',
    },
    userInfoSection: {
        flex: 1,
    },
    userNameText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#fff',
    },
    userNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 4,
    },
    preferencesStatusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    preferencesStatusTextGreen: {
        fontSize: 12,
        color: '#10b981',
        fontWeight: '500',
    },
    preferencesStatusTextPurple: {
        fontSize: 12,
        color: '#8b5cf6',
        fontWeight: '500',
    },
    preferencesStatusTextOrange: {
        fontSize: 12,
        color: '#f59e0b',
        fontWeight: '500',
    },
    hostRequestContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 4,
    },
    hostRequestText: {
        fontSize: 15,
        color: '#8b5cf6',
        fontWeight: '600',
        lineHeight: 20,
        flex: 1,
    },
    socialActionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 24,
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    socialActionSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.7)',
        marginBottom: 20,
        textAlign: 'center',
        lineHeight: 20,
    },
    optionsContainer: {
        flexDirection: 'row',
        gap: 12,
        justifyContent: 'space-between',
    },
    optionCard: {
        flex: 1,
        backgroundColor: 'rgba(32, 25, 37, 0.6)',
        backdropFilter: 'blur(10px)',
        borderWidth: 1,
        borderColor: 'rgba(139, 92, 246, 0.2)',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 12,
        alignItems: 'center',
        minHeight: 100,
        justifyContent: 'center',
        gap: 8,
    },
    optionCardActive: {
        backgroundColor: 'rgba(139, 92, 246, 0.15)',
        borderColor: '#8b5cf6',
        borderWidth: 2,
        shadowColor: '#8b5cf6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    optionCardDisabled: {
        backgroundColor: 'rgba(32, 25, 37, 0.4)',
        borderColor: 'rgba(107, 114, 128, 0.15)',
        opacity: 0.5,
    },
    optionIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(139, 92, 246, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    optionIconActive: {
        backgroundColor: '#8b5cf6',
        shadowColor: '#8b5cf6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 4,
    },
    optionTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#fff',
        textAlign: 'center',
        letterSpacing: 0.3,
    },
    optionTitleDisabled: {
        color: '#9ca3af',
    },
    optionDescription: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.6)',
        textAlign: 'center',
        lineHeight: 16,
    },
    optionDescriptionDisabled: {
        color: '#6b7280',
    },
    activeIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: 'rgba(139, 92, 246, 0.2)',
        width: '100%',
        justifyContent: 'center',
    },
    activeIndicatorText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#8b5cf6',
    },
    activeIndicatorCompact: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: 'rgba(16, 185, 129, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    updateButtonFull: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(168, 85, 247, 0.1)',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(168, 85, 247, 0.3)',
        gap: 8,
        marginTop: 16,
    },
    actionGradient: {
        padding: 24,
        alignItems: 'center',
        backgroundColor: 'transparent',
    },
    actionIconBg: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(147, 51, 234, 0.15)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    actionTitle: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: '700',
        marginBottom: 8,
    },
    actionText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 20,
        paddingHorizontal: 20,
        lineHeight: 20,
    },
    modernActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#9333EA',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 14,
        gap: 8,
        shadowColor: '#9333EA',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    modernActionButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '700',
    },
    checkCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    submittedHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    updateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(168, 85, 247, 0.1)',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(168, 85, 247, 0.3)',
        gap: 8,
    },
    updateButtonText: {
        color: '#A855F7',
        fontSize: 14,
        fontWeight: '600',
    },
    compactCounterWrapper: {
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    compactCounter: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(147, 51, 234, 0.1)',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 25,
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.2)',
        gap: 8,
    },
    compactNumber: {
        color: '#A855F7',
        fontSize: 20,
        fontWeight: '700',
    },
    compactLabel: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 14,
        fontWeight: '500',
    },
    collectingPhaseTitle: {
        color: '#fff',
        fontSize: 24,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        marginBottom: 16,
        textAlign: 'center',
    },
    viewDetailsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginTop: 10,
        marginBottom: 6,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    viewDetailsButtonText: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 13,
        fontWeight: '500',
        marginRight: 6,
    },
    cardPriceCorner: {
        position: 'absolute',
        top: 0,
        right: 0,
        color: '#D4AF37',
        fontSize: 16,
        fontWeight: '600',
    },
    cardTitleContainer: {
        flex: 1,
        paddingRight: 60, // Make room for price
    },

    // Finalized Plan Card Styles (modernized)
    finalizedPlanCard: {
        backgroundColor: 'rgba(32, 25, 37, 0.95)',
        borderRadius: 24,
        marginHorizontal: 16,
        marginBottom: 20,
        overflow: 'hidden',
        padding: 24,
        shadowColor: 'rgba(147, 51, 234, 0.4)',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 1,
        shadowRadius: 16,
        elevation: 8,
        borderWidth: 2,
        borderColor: 'rgba(147, 51, 234, 0.3)',
    },
    finalizedPlanCardGradientBorder: {
        borderRadius: 24,
        padding: 2,
    },
    finalizedPlanCardInner: {
        backgroundColor: 'rgba(32, 25, 37, 0.95)',
        borderRadius: 22,
        padding: 24,
    },
    finalizedActivityTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#fff',
        flex: 1,
        textShadowColor: 'rgba(147, 51, 234, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    eventDateBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(147, 51, 234, 0.15)',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginTop: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.3)',
        gap: 12,
    },
    eventDateIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(147, 51, 234, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    eventDateIcon: {
        marginRight: 16,
    },
    eventDateTextContainer: {
        flex: 1,
    },
    eventDateText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.3,
        lineHeight: 20,
    },
    eventTimeText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 13,
        fontWeight: '500',
        letterSpacing: 0.3,
        marginTop: 2,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
        letterSpacing: 0.5,
        flex: 1,
    },
    placeName: {
        fontSize: 24,
        fontWeight: '700',
        color: '#9333ea',
        marginBottom: 12,
        textShadowColor: 'rgba(147, 51, 234, 0.2)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    placeDescription: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.75)',
        marginBottom: 16,
        lineHeight: 22,
    },
    placeAddress: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.85)',
        fontWeight: '500',
        marginLeft: 8,
        flex: 1,
    },
    placePrice: {
        fontSize: 16,
        color: '#fbbf24',
        fontWeight: '700',
        letterSpacing: 0.5,
        marginLeft: 8,
    },
    primaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#9333ea',
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 20,
        gap: 8,
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
        borderWidth: 1.5,
        borderColor: 'rgba(147, 51, 234, 0.5)',
    },
    primaryButtonIcon: {
        fontSize: 18,
        marginRight: 8,
    },
    primaryButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    actionButtons: {
        width: '100%',
        marginTop: 4,
    },
    secondaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(147, 51, 234, 0.1)',
        borderRadius: 14,
        padding: 16,
        flex: 1,
        gap: 8,
        borderWidth: 1.5,
        borderColor: 'rgba(147, 51, 234, 0.3)',
    },
    secondaryButtonIcon: {
        fontSize: 18,
        marginRight: 8,
    },
    secondaryButtonText: {
        color: '#9333ea',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0.3,
    },
    welcomeMessage: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.85)',
        lineHeight: 22,
        fontStyle: 'italic',
    },
    attendeePills: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    attendeePill: {
        backgroundColor: 'rgba(147, 51, 234, 0.15)',
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.3)',
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    attendeePillText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
    attendeeProfilePic: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: 'rgba(147, 51, 234, 0.3)',
        borderWidth: 1.5,
        borderColor: 'rgba(147, 51, 234, 0.5)',
    },
    hostProfilePic: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: 'rgba(251, 191, 36, 0.3)',
        borderWidth: 1.5,
        borderColor: 'rgba(251, 191, 36, 0.6)',
    },
    finalizedIconContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 12,
        position: 'relative',
    },
    finalizedEditButton: {
        position: 'absolute',
        top: 0,
        right: 0,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(147, 51, 234, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: 'rgba(147, 51, 234, 0.4)',
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 2,
    },
    finalizedIconCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#9333ea',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 3,
    },
    finalizedStatusSubtext: {
        fontSize: 11,
        color: 'rgba(255, 255, 255, 0.5)',
        textTransform: 'uppercase',
        letterSpacing: 1,
        fontWeight: '600',
        marginTop: 2,
    },
    finalizedTitleContainer: {
        flex: 1,
        paddingRight: 44,
    },
    finalizedHostMessageContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginTop: 12,
        gap: 10,
    },
    finalizedHostProfilePic: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(147, 51, 234, 0.3)',
        borderWidth: 2,
        borderColor: 'rgba(147, 51, 234, 0.5)',
    },
    finalizedHostMessage: {
        flex: 1,
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.7)',
        lineHeight: 19,
        fontStyle: 'italic',
        paddingLeft: 12,
        borderLeftWidth: 3,
        borderLeftColor: 'rgba(147, 51, 234, 0.4)',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        gap: 12,
    },
    placeDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    hostPill: {
        backgroundColor: 'rgba(251, 191, 36, 0.12)',
        borderColor: 'rgba(251, 191, 36, 0.35)',
    },

    finalizedHeader: {
        backgroundColor: '#28a745',
        paddingVertical: 12,
        paddingHorizontal: 16,
        alignItems: 'center',
    },

    finalizedStatusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },

    finalizedStatusText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
    },

    selectedPlaceSection: {
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(64, 51, 71, 0.3)',
    },

    selectedPlaceHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },

    selectedPlaceName: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        flex: 1,
        marginRight: 12,
    },

    selectedPlaceDetails: {
        gap: 8,
    },

    selectedPlaceDetail: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },

    selectedPlaceDetailText: {
        color: '#B8A5C4',
        fontSize: 14,
        fontWeight: '500',
    },

    finalizedActionSection: {
        padding: 20,
    },

    finalizedShareButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cc31e8',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        gap: 8,
    },

    finalizedShareButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Montserrat_600SemiBold',
    },
    
    // New card grid styles for voting phase - flush with edges like community feed
    recommendationsGrid: {
        paddingHorizontal: 0,
        paddingTop: 0,
        paddingBottom: 0,
    },
    participantViewHeader: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
        alignItems: 'center',
    },
    participantViewTitle: {
        fontSize: 14,
        fontWeight: '500',
        color: 'rgba(255, 255, 255, 0.7)',
        marginBottom: 8,
        textAlign: 'center',
        lineHeight: 20,
    },
    participantViewSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.7)',
        textAlign: 'center',
    },
    participantNote: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(184, 165, 196, 0.1)',
        borderRadius: 12,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(184, 165, 196, 0.2)',
    },
    participantNoteText: {
        flex: 1,
        marginLeft: 12,
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
        lineHeight: 20,
    },
    recommendationCard: {
        flexDirection: 'row',
        backgroundColor: 'rgba(42, 30, 46, 0.6)',
        borderRadius: 0,
        padding: 16,
        marginBottom: 0,
        borderBottomWidth: 1,
        borderColor: 'rgba(185, 84, 236, 0.25)',
        alignItems: 'flex-start',
    },
    recommendationCardFavorited: {
        backgroundColor: 'rgba(212, 175, 55, 0.08)',
        borderLeftWidth: 3,
        borderLeftColor: '#D4AF37',
    },
    recCardContent: {
        flex: 1,
        marginRight: 12,
    },
    recCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    recCardTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    recCardTitle: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
        flex: 1,
    },
    recCardPriceTag: {
        backgroundColor: 'rgba(251, 191, 36, 0.15)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    recCardPrice: {
        color: '#fbbf24',
        fontSize: 12,
        fontWeight: '700',
        fontFamily: 'Montserrat_700Bold',
    },
    recCardDescription: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
        lineHeight: 19,
        marginBottom: 8,
    },
    recCardAddressRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 4,
    },
    recCardAddressText: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 13,
        flex: 1,
    },
    recCardInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
        gap: 6,
    },
    recCardInfoText: {
        color: 'rgba(255, 255, 255, 0.85)',
        fontSize: 13,
        flex: 1,
        fontWeight: '500',
    },
    recCardReason: {
        color: 'rgba(255, 255, 255, 0.75)',
        fontSize: 13,
        lineHeight: 18,
        marginTop: 6,
        fontWeight: '400',
    },
    recCardActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(30, 30, 35, 0.95)',
        paddingHorizontal: 12,
        paddingBottom: 10,
        paddingTop: 4,
        gap: 10,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.05)',
    },
    recActionButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.15)',
    },
    recActionButtonActive: {
        backgroundColor: 'rgba(231, 76, 60, 0.25)',
        borderColor: '#e74c3c',
    },
    recActionButtonFavorited: {
        backgroundColor: 'rgba(212, 175, 55, 0.25)',
        borderColor: '#D4AF37',
    },
    recCardChevron: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 8,
        alignSelf: 'center',
    },
    bottomActionsContainer: {
        paddingHorizontal: 16,
        marginTop: 8,
        paddingBottom: 30,
        gap: 12,
    },
    buttonDisabled: {
        opacity: 0.5,
    },
    
    // View Mode Toggle Styles
    viewModeToggle: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        gap: 8,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    viewModeToggleOverlay: {
        position: 'absolute',
        top: 5,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        gap: 0,
        zIndex: 100,
    },
    cardsContainer: {
        flex: 1,
        paddingTop: 0,
    },
    viewModeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 25,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        gap: 8,
        backdropFilter: 'blur(10px)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    viewModeButtonActive: {
        backgroundColor: '#cc31e8',
        borderColor: '#cc31e8',
    },
    viewModeButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#999',
    },
    viewModeButtonTextActive: {
        color: '#fff',
    },
    scrollContainer: {
        flex: 1,
    },
    
    // Full screen container for fixed map view
    fullScreenContainer: {
        flex: 1,
        backgroundColor: '#201925',
    },
    mapContainer: {
        flex: 1,
    },
    mapViewContainer: {
        flex: 1,
        width: '100%',
        backgroundColor: '#201925',
        overflow: 'visible',
    },
    fixedBottomActions: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: 16,
        paddingBottom: 30,
        paddingTop: 16,
        backgroundColor: 'rgba(32, 25, 37, 0.95)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
        gap: 12,
    },
    // Tag styles for keyword display
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
        marginTop: 8,
    },
    tagPill: {
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderWidth: 1,
        borderColor: 'rgba(204, 49, 232, 0.3)',
    },
    tagText: {
        color: '#cc31e8',
        fontSize: 12,
        fontWeight: '600',
    },
    recCardTags: {
        marginTop: 6,
        marginBottom: 12,
    },
    detailTags: {
        marginTop: 8,
    },

    // Finalized Venue Card Styles (modernized to match collecting/voting phases)
    finalizedVenueCard: {
        backgroundColor: 'rgba(32, 25, 37, 0.95)',
        borderRadius: 24,
        marginHorizontal: 16,
        marginBottom: 20,
        overflow: 'hidden',
        shadowColor: 'rgba(147, 51, 234, 0.4)',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 1,
        shadowRadius: 16,
        elevation: 8,
    },
    finalizedVenueCardGradientBorder: {
        borderRadius: 24,
        padding: 2,
    },
    finalizedVenueCardInner: {
        backgroundColor: 'rgba(32, 25, 37, 0.95)',
        borderRadius: 22,
        padding: 24,
    },
    // Collecting Phase Cards
    collectingCardGradientBorder: {
        borderRadius: 24,
        padding: 2,
        shadowColor: 'rgba(147, 51, 234, 0.3)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 1,
        shadowRadius: 12,
        elevation: 8,
    },
    collectingCardInner: {
        backgroundColor: 'rgba(32, 25, 37, 0.95)',
        borderRadius: 22,
        padding: 20,
    },
    collectingSectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 10,
    },
    collectingIconWrapper: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(147, 51, 234, 0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    collectingSectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#ffffff',
        fontFamily: 'Montserrat_700Bold',
    },
    finalizedVenueHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        gap: 12,
    },
    finalizedVenueIconWrapper: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(147, 51, 234, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'rgba(147, 51, 234, 0.4)',
    },
    finalizedVenueSectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
        letterSpacing: 0.5,
    },
    finalizedVenueHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    finalizedVenueTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: '#fff',
        flex: 1,
        marginRight: 12,
        lineHeight: 28,
    },
    finalizedPriceTag: {
        backgroundColor: 'rgba(251, 191, 36, 0.2)',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(251, 191, 36, 0.3)',
    },
    finalizedPriceText: {
        color: '#fbbf24',
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    finalizedVenueDescription: {
        color: 'rgba(255, 255, 255, 0.75)',
        fontSize: 14,
        lineHeight: 22,
        marginBottom: 16,
    },
    finalizedVenueMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(147, 51, 234, 0.08)',
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 12,
        marginBottom: 20,
        gap: 8,
        borderWidth: 1,
        borderColor: 'rgba(147, 51, 234, 0.15)',
    },
    finalizedVenueAddress: {
        color: 'rgba(255, 255, 255, 0.85)',
        fontSize: 14,
        flex: 1,
        lineHeight: 20,
        fontWeight: '500',
    },
    // Venue Details Grid
    finalizedDetailsGrid: {
        gap: 12,
        marginBottom: 20,
    },
    finalizedDetailCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        paddingVertical: 12,
        paddingHorizontal: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(139, 92, 246, 0.2)',
        gap: 12,
    },
    finalizedDetailIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(168, 85, 247, 0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    finalizedDetailContent: {
        flex: 1,
    },
    finalizedDetailLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: 'rgba(255, 255, 255, 0.6)',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 4,
    },
    finalizedDetailValue: {
        fontSize: 14,
        fontWeight: '500',
        color: '#ffffff',
        lineHeight: 20,
    },
    finalizedVenueActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 4,
    },
    finalizedActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 44,
        borderRadius: 14,
        backgroundColor: 'rgba(147, 51, 234, 0.15)',
        borderWidth: 1.5,
        borderColor: 'rgba(147, 51, 234, 0.3)',
        gap: 6,
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
        elevation: 2,
    },
    finalizedActionButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 0.3,
    },

    // Delete Activity Button Styles
    deleteActivitySection: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
        paddingVertical: 16,
        paddingHorizontal: 20,
        marginTop: 24,
    },

    deleteActivityButton: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        alignItems: 'center',
        flex: 1,
        backgroundColor: 'rgba(239, 68, 68, 0.05)',
        borderRadius: 8,
        marginHorizontal: 6,
    },

    deleteActivityButtonText: {
        color: '#ef4444',
        fontSize: 14,
        fontWeight: '600',
    },

    leaveActivityButton: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        alignItems: 'center',
        flex: 1,
        backgroundColor: 'rgba(239, 68, 68, 0.05)',
        borderRadius: 8,
        marginHorizontal: 6,
    },

    leaveActivityButtonText: {
        color: '#ef4444',
        fontSize: 14,
        fontWeight: '600',
    },

    reportActivityButton: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        alignItems: 'center',
        flex: 1,
        backgroundColor: 'rgba(255, 165, 0, 0.05)',
        borderRadius: 8,
        marginHorizontal: 6,
    },

    reportActivityButtonText: {
        color: '#FFA500',
        fontSize: 14,
        fontWeight: '600',
    },

    // Finalize Button - Top Position (Subtle Style)
    finalizeContainer: {
        backgroundColor: 'rgba(147, 51, 234, 0.08)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(147, 51, 234, 0.15)',
    },

    finalizeButtonTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
    },

    finalizeTextContainer: {
        flex: 1,
        marginLeft: 12,
        marginRight: 12,
    },

    finalizeButtonTopText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#cc31e8',
        marginBottom: 4,
    },

    finalizeButtonSubtitle: {
        fontSize: 13,
        fontWeight: '400',
        color: 'rgba(204, 49, 232, 0.7)',
        lineHeight: 18,
    },

    // Complete Button Styles (for solo activities) - Green theme
    completeButtonText: {
        color: '#10b981',
    },

    completeButtonSubtitle: {
        color: 'rgba(16, 185, 129, 0.7)',
    },

    // Finalize Button Section - Bottom Position (kept for backward compatibility)
    finalizeSection: {
        paddingHorizontal: 20,
        paddingVertical: 24,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.05)',
        marginTop: 16,
    },

    finalizeButton: {
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },

    finalizeButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        paddingHorizontal: 24,
        gap: 10,
    },

    finalizeButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0.3,
    },

    // Participant Note - Top Position
    participantNoteTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 16,
        backgroundColor: 'rgba(184, 165, 196, 0.05)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(184, 165, 196, 0.1)',
    },
});

export default styles;